version: '3'

services:
  app:
    build: .
    environment:
      - PORT=80
      - DEBUG=true
      - PLAYGROUND=/playground
    volumes:
      - ./serviceAccount.json:/usr/src/app/serviceAccount.json
      - ./schema.graphql:/usr/src/app/schema.graphql
    ports:
      - "80:80"